In [1]:
import numpy as np

print(np.__version__)

2.5.1


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
#cast a list into an array
my_list = [1, 2, 3, 4, 5]
arr= np.array(my_list)
print(arr)

[1 2 3 4 5]


In [6]:
#get a 2d array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# array range (start, stop, step)
a= np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [9]:
# array of zeros (rows, columns)
z= np.zeros((2, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# array of ones (rows, columns)
o= np.ones((3, 4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# array of evenly spaced numbers over a specified interval (start, stop, number of samples)
s= np.linspace(0, 10, 5)
print(s)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
# identity matrix (size)
i= np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# array of random numbers (rows, columns)
r= np.random.rand(5,2)
print(r)

array([[0.22758065, 0.59660644],
       [0.49883854, 0.01141342],
       [0.56708124, 0.51821902],
       [0.1239202 , 0.58307696],
       [0.77655549, 0.84899979]])

In [14]:
# from standard normal distribution or from a gaussion distribution
n= np.random.randn(3, 4)
print(n)

[[ 0.13579507 -1.89830645 -0.11534526  1.16121029]
 [ 0.66121716  0.58898239  0.61439397 -1.32590472]
 [-1.03316978  1.71659835  0.7351259  -0.6187324 ]]


In [15]:
# array of random integers (low, high, size)
m= np.random.randint(1, 10, (3, 4))
print(m)

[[8 5 1 1]
 [9 7 1 6]
 [7 5 8 2]]


In [19]:
# reshape an array
m= m.reshape(5, 1)
print(m)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [20]:
# maximum and minimum values
max_val = np.max(m)
print("Maximum value:", max_val)
min_val = np.min(m)
print("Minimum value:", min_val)

Maximum value: 5
Minimum value: 1


In [21]:
# index of maximum and minimum values
max_index = np.argmax(m)
print("Index of maximum value:", max_index)
min_index = np.argmin(m)
print("Index of minimum value:", min_index)

Index of maximum value: 4
Index of minimum value: 0


In [22]:
# shape of an array , no parenthesis needed
shape = m.shape
print("Shape of the array:", shape)

Shape of the array: (5, 1)


In [25]:
from numpy.random import randint
print (randint(1, 4, size=(3, 4)))

[[2 3 1 2]
 [3 3 1 1]
 [3 3 2 1]]


In [41]:
ar= np.arange(0, 11)
print(ar)
print(ar[8])
print(ar[1:5])
print(ar[5:])

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]
[ 5  6  7  8  9 10]


In [42]:
#NUMPY ARRAYS DIFFER FROM array lists because of their ability to broadcast.
# This allows for element-wise operations on arrays of different shapes.
#  This makes numpy arrays more efficient for numerical computations compared to standard Python lists.

slice= ar[0:6]
print(slice)

[0 1 2 3 4 5]


In [39]:
slice[:]= 99
print(slice)
print (ar)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [43]:
ar_copy= ar.copy()
ar_copy[:]= 100
print(ar_copy)

[100 100 100 100 100 100 100 100 100 100 100]


In [45]:
ar2d= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ar2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
ar2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [50]:
print (ar)
bool_ar= ar > 5
print(bool_ar)
print(ar[bool_ar])

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [51]:
print(ar[ar>5])

[ 6  7  8  9 10]


In [52]:
arr_2d= np.arange(50).reshape(5, 10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [55]:
# include the first index, exclude the last index
print(arr_2d[2:4,4:7])

[[24 25 26]
 [34 35 36]]


In [59]:
arrr= np.arange(0, 11)
print(arrr)
print(arrr + arrr)
print(arrr - arrr)
print(arrr * arrr)
print(arrr - 100)
print(arrr **2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[  0   1   4   9  16  25  36  49  64  81 100]


In [57]:
print(arrr / arrr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\shali\AppData\Local\Temp\ipykernel_19192\400884425.py:1: RuntimeWarning: invalid value encountered in divide
  print(arrr / arrr)


In [58]:
print(1/arrr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


C:\Users\shali\AppData\Local\Temp\ipykernel_19192\2832226947.py:1: RuntimeWarning: divide by zero encountered in divide
  print(1/arrr)


In [62]:
print(np.sqrt(arrr))
print(np.exp(arrr))
print(np.max(arrr))
print(np.sin(arrr))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
