In [1]:
import numpy as np

In [2]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
print(np.arange(10, 51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
print(np.arange(10, 51, 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [8]:
print(np.arange(0, 9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print(np.random.rand(1))

[0.35314099]


In [16]:
print(np.random.randn(25))

[ 1.94694193 -1.0294796   1.05854348 -0.22987006  0.61190241  1.16048335
 -0.56545     1.04345084 -1.23143945 -1.68628328  0.14845263 -2.53237513
 -0.29127072  0.30592032  0.02741211 -1.33663404  0.62410019 -0.03793057
  1.12821563  2.18001298  0.05162017  1.08815869 -0.43252079 -0.17389878
  1.62599617]


In [21]:
m= np.arange(0,100).reshape(10,10)/100
print (m)

[[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


In [22]:
print(np.linspace(0, 1, 20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [43]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [31]:
print(mat[3,4])

20


In [42]:
print(mat[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [41]:
print(mat[4,:])

[21 22 23 24 25]


In [40]:
print(mat[3:5,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
print(mat.sum())

325


In [38]:
print(mat.std())

7.211102550927978


In [37]:
print(mat.sum(axis=0))

[55 60 65 70 75]
